/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sample } from './sample';
import { AnalysisTypeId } from './analysisTypeId';


export interface Analysis { 
    analysisId?: string;
    analysisType?: AnalysisTypeId;
    analysisState?: string;
    updatedAt?: string;
    publishedAt?: string;
    firstPublishedAt?: string;
    studyId?: string;
    files?: Array<any>;
    samples?: Array<Sample>;
    experiment?: { [key: string]: object; };
}

