/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelFile { 
    objectId?: string;
    studyId?: string;
    analysisId?: string;
    fileName?: string;
    fileType?: string;
    fileMd5sum?: string;
    fileAccess?: string;
    dataType?: string;
    fileSize?: number;
    info?: { [key: string]: object; };
}

