/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Specimen } from './specimen';
import { Donor } from './donor';


export interface Sample { 
    sampleId?: string;
    specimenId?: string;
    submitterSampleId?: string;
    matchedNormalSubmitterSampleId?: string;
    sampleType?: string;
    donor?: Donor;
    specimen?: Specimen;
    info?: { [key: string]: object; };
}

