export * from './analysis.service';
import { AnalysisService } from './analysis.service';
export * from './donor.service';
import { DonorService } from './donor.service';
export * from './export.service';
import { ExportService } from './export.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './legacyEntity.service';
import { LegacyEntityService } from './legacyEntity.service';
export * from './sample.service';
import { SampleService } from './sample.service';
export * from './schema.service';
import { SchemaService } from './schema.service';
export * from './specimen.service';
import { SpecimenService } from './specimen.service';
export * from './study.service';
import { StudyService } from './study.service';
export * from './submit.service';
import { SubmitService } from './submit.service';
export const APIS = [AnalysisService, DonorService, ExportService, FileService, HealthService, LegacyEntityService, SampleService, SchemaService, SpecimenService, StudyService, SubmitService];
