/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { Application } from './application';


export interface ApplicationPermission { 
    accessLevel?: ApplicationPermission.AccessLevelEnum;
    id?: string;
    owner?: Application;
    policy?: Policy;
}
export namespace ApplicationPermission {
    export type AccessLevelEnum = 'READ' | 'WRITE' | 'DENY';
    export const AccessLevelEnum = {
        Read: 'READ' as AccessLevelEnum,
        Write: 'WRITE' as AccessLevelEnum,
        Deny: 'DENY' as AccessLevelEnum
    };
}


