/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Application { 
    clientId?: string;
    clientSecret?: string;
    description?: string;
    errorRedirectUri?: string;
    id?: string;
    name?: string;
    redirectUri?: string;
    status?: Application.StatusEnum;
    type?: Application.TypeEnum;
}
export namespace Application {
    export type StatusEnum = 'APPROVED' | 'DISABLED' | 'PENDING' | 'REJECTED';
    export const StatusEnum = {
        Approved: 'APPROVED' as StatusEnum,
        Disabled: 'DISABLED' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
    export type TypeEnum = 'CLIENT' | 'ADMIN';
    export const TypeEnum = {
        Client: 'CLIENT' as TypeEnum,
        Admin: 'ADMIN' as TypeEnum
    };
}


