/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupRequest { 
    description?: string;
    name?: string;
    status?: GroupRequest.StatusEnum;
}
export namespace GroupRequest {
    export type StatusEnum = 'APPROVED' | 'DISABLED' | 'PENDING' | 'REJECTED';
    export const StatusEnum = {
        Approved: 'APPROVED' as StatusEnum,
        Disabled: 'DISABLED' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


