/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OAuth2RefreshToken } from './oAuth2RefreshToken';


export interface OAuth2AccessToken { 
    additionalInformation?: object;
    expiration?: string;
    expired?: boolean;
    expiresIn?: number;
    refreshToken?: OAuth2RefreshToken;
    scope?: Array<string>;
    tokenType?: string;
    value?: string;
}

