/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPermission } from './userPermission';


export interface PageDTOUserPermission { 
    count?: number;
    limit?: number;
    offset?: number;
    resultSet?: Array<UserPermission>;
}

