/**
 * Ego Service API
 * Ego API Documentation
 *
 * The version of the OpenAPI document: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequest { 
    firstName?: string;
    lastName?: string;
    preferredLanguage?: UpdateUserRequest.PreferredLanguageEnum;
    status?: UpdateUserRequest.StatusEnum;
    type?: UpdateUserRequest.TypeEnum;
}
export namespace UpdateUserRequest {
    export type PreferredLanguageEnum = 'ENGLISH' | 'FRENCH' | 'SPANISH';
    export const PreferredLanguageEnum = {
        English: 'ENGLISH' as PreferredLanguageEnum,
        French: 'FRENCH' as PreferredLanguageEnum,
        Spanish: 'SPANISH' as PreferredLanguageEnum
    };
    export type StatusEnum = 'APPROVED' | 'DISABLED' | 'PENDING' | 'REJECTED';
    export const StatusEnum = {
        Approved: 'APPROVED' as StatusEnum,
        Disabled: 'DISABLED' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
    export type TypeEnum = 'USER' | 'ADMIN';
    export const TypeEnum = {
        User: 'USER' as TypeEnum,
        Admin: 'ADMIN' as TypeEnum
    };
}


